### ISSUE TITLE
Simplified affiliate page

### ISSUE THREAD

**Issue by bf-tom** [betfinio/affiliate#124]
We intend to setup a simplified version of link generation for newbies that is gonna be the default one on affiliate page. We will hide the feature of matched and unmatched volume and will display the total volume instead. Those 2 borders with volumes (left/right) will work as big buttons for generation of straight line academy link to left or right leg. 
- Those links for left or strong leg should remain the same for each user.
- The option of current advanced selection will remain as a button next to the generation of link - that will work absolutely the same as it works now. 
![Image](https://github.com/user-attachments/assets/1470ba83-22de-40d7-9555-6065f3bc3c9d)

See the closer specification of the simplification feature:

1. Weak leg always pre selected so user just picks the better link. If legs are the same left is default. 
2. Invitation Button changing caption depending to which leg you are creating link to
3. if your legs have both 0, show only yellow invitation button with caption: create invitation link. Hide everything else.
4. invitation link creates Straight link to that leg.
5. invitation link Straight link logic needs to be adjusted so it will go to weak leg even if it doesnt exist. That is edge case where first user creates the leg then the rest works the same. 
6. existing affilaite tools: create button with caption: "Advanced mode" and when you click it, old userform will expand

**Comment by bf-monster** [comment]
@bf-tom  will there be new design for this page?

**Comment by bf-tom** [comment]
@bf-monster yes, I am on it

**Comment by bf-monster** [comment]
-[ ] advanced settings

**Comment by bf-tom** [comment]
accepted by Mike, but please do not release to production yet
