### ISSUE TITLE
extract locales - affiliate

### ISSUE THREAD

**Issue by bf-monster** [betfinio/affiliate#18]

**Comment by bf-monster** [comment]
table navigation will be fixed later

**Comment by bf-gabagool** [comment]
![Image](https://github.com/user-attachments/assets/4d673c0b-7841-4309-8cd2-232b077700dc)
Fix declension of endings (1 vysledek, 2-4 vysledky, 5 and more = výsledků) + selected to výbrano

Besides that everything is good
