### ISSUE TITLE
Add the option to find exact address in binary tree

### ISSUE THREAD

**Issue by bf-monster** [betfinio/affiliate#45]

**Comment by bf-monster** [comment]
requires more time. maybe after #48

**Comment by BF-MAGNUM** [comment]
This becomes demanded @bf-monster

**Comment by bf-monster** [comment]
- [ ] Once we have the option to search a user in genealogy tree, there should be a button to open user in genealogy tree. That should be a button visible in users profile detail, put it bellow the up line wallet. Button should open a genealogy binary tree with expanded tree from signed member to this particular user.
